### ISSUE TITLE
Invalid enum value. Expected '2captcha' | 'capsolver', received ''

### ISSUE THREAD

**Issue by TracyZhou619** [phamleduy04/texas-dps-scheduler#178]
![image](https://github.com/user-attachments/assets/8f3b3591-52bf-49e7-b256-878a9964ee5a)
![image](https://github.com/user-attachments/assets/394f0524-01f4-4977-a51c-3888db4b7b61)
I was trying to use the manual token way and I tried putting "solver" / "browser" here but both don't work. Please help!

**Comment by phamleduy04** [comment]
will fix soon this

**Comment by phamleduy04** [comment]
if you do this it will be fine with the next version

```yaml
  captcha:
    # Avaliable options: solver or browser
    strategy: 'browser'
    solverOptions:
      # Avaliable options: capsolver
      solverService: ''
      solverApiToken: ''
```
