### ISSUE TITLE
[BUG] ERROR: Error while getting captcha token:

### ISSUE THREAD

**Issue by manfredwang093** [phamleduy04/texas-dps-scheduler#213]
Getting below error where I don't any open issue sharing the same, can anyone help?
```
npm run start

> texas-dps-scheduler@5.1.3 start
> ts-node --transpile-only src/index.ts

[04/29/2025 10:48:10] Texas Scheduler v5.1.3 is starting...
[04/29/2025 10:48:10] Requesting Available Location....
[04/29/2025 10:48:48] ERROR: Error while getting captcha token:
ProtocolError: Protocol error (Fetch.enable): 'Fetch.enable' wasn't found
    at Callback.<instance_members_initializer> (/Users/manfred/Downloads/driving_liscense/texas-dps-scheduler/node_modules/puppeteer-core/src/common/CallbackRegistry.ts:125:12)
    at new Callback (/Users/manfred/Downloads/driving_liscense/texas-dps-scheduler/node_modules/puppeteer-core/src/common/CallbackRegistry.ts:130:3)
    at CallbackRegistry.create (/Users/manfred/Downloads/driving_liscense/texas-dps-scheduler/node_modules/puppeteer-core/src/common/CallbackRegistry.ts:28:22)
    at Connection._rawSend (/Users/manfred/Downloads/driving_liscense/texas-dps-scheduler/node_modules/puppeteer-core/src/cdp/Connection.ts:136:22)
    at CdpCDPSession.send (/Users/manfred/Downloads/driving_liscense/texas-dps-scheduler/node_modules/puppeteer-core/src/cdp/CdpSession.ts:103:29)
    at NetworkManager.#applyProtocolRequestInterception (/Users/manfred/Downloads/driving_liscense/texas-dps-scheduler/node_modules/puppeteer-core/src/cdp/NetworkManager.ts:267:16)
    at /Users/manfred/Downloads/driving_liscense/texas-dps-scheduler/node_modules/puppeteer-core/src/cdp/NetworkManager.ts:207:16
    at Array.map (<anonymous>)
    at NetworkManager.#applyToAllClients (/Users/manfred/Downloads/driving_liscense/texas-dps-scheduler/node_modules/puppeteer-core/src/cdp/NetworkManager.ts:206:40)
    at NetworkManager.setRequestInterception (/Users/manfred/Downloads/driving_liscense/texas-dps-scheduler/node_modules/puppeteer-core/src/cdp/NetworkManager.ts:255:34)
[04/29/2025 10:48:48] Try to get captcha token again or manual set it in config.yml
```

Here is my config:
```
appSettings:
  # Put true/false without quotes if you want to cancel the appointment automatically if found existing appointment
  cancelIfExist: false
  # The time interval (in ms) the app will recheck for newer dates
  interval: 10000
  # Set this to true if you using replit, heroku or something equivalent
  webserver: false
  # Set this to higher if you encounter Header Timeout error. This one is in miliseconds
  headersTimeout: 50000 
  # How many times to retry if the request to DPS server failled
  maxRetry: 3
  # Read this for more infomation: https://github.com/phamleduy04/texas-dps-scheduler/wiki/Captcha-(Auth-Token)
  captcha:
    # Avaliable options: solver, browser or manual
    strategy: 'browser'
    # solverOptions:
    #   solverService: 'capsolver'
    #   solverApiToken: ''
  # ntfy.sh push notification
  pushNotifcation:
    enabled: false
    baseURL: ''
    topicName: ''
    token: ''
```
