### ISSUE TITLE
Error while getting captcha token:

### ISSUE THREAD

**Issue by adamkhan47** [phamleduy04/texas-dps-scheduler#221]
Whenever the app crashes randomly when using browser ( i am using the pull request so browser works ) it makes me wait hours for it to let me work because somethings off. I tried even using VPN and it didnt work
Error below
```
[06/17/2025 4:36:28] Texas Scheduler v5.1.4 is starting...
[06/17/2025 4:36:28] Requesting Available Location....
[06/17/2025 4:37:43] ERROR: Error while getting captcha token:
Error: Auth token retrieval timed out after 60 seconds
    at Timeout._onTimeout (/Users/adamkhan/Documents/texas-dps-scheduler-main/src/Browser/index.ts:76:53)
    at listOnTimeout (node:internal/timers:573:17)
    at processTimers (node:internal/timers:514:7)
[06/17/2025 4:37:43] Try to get captcha token again or manual set it in config.yml
```
heres my app settings
```
cancelIfExist: false
  # The time interval (in ms) the app will recheck for newer dates
  interval: 20000
  # Set this to true if you using replit, heroku or something equivalent
  webserver: false
  # Set this to higher if you encounter Header Timeout error. This one is in miliseconds
  headersTimeout: 50000 
  # How many times to retry if the request to DPS server failled
  maxRetry: 399
  # Read this for more infomation: https://github.com/phamleduy04/texas-dps-scheduler/wiki/Captcha-(Auth-Token)
  captcha:
    # Avaliable options: solver, browser or manual
    strategy: 'browser'
    solverOptions:
      solverService: 'capsolver'
      solverApiToken: ''
```
